Disable Global ThinLto by default
* breaks compilation on devices that uses virtualization

ut/soong/.intermediates/packages/modules/Virtualization/vmbase/libvmbase/android_arm64_armv8-2a-dotprod_cortex-a76_rlib_rlib-std/libvmbase.rlib
Error: exited with code: 1
Command: OUT_DIR=out ANDROID_RUST_VERSION=1.68.0 AR=prebuilts/clang/host/linux-x86/clang-r498229b/bin/llvm-ar prebuilts/rust/linux-x86/1.68.0/bin/rustc -C linker=build/soong/scripts/mkcratersp.py --emit link -o out/soong/.intermediates/p>
Output:
^[[0m^[[1m^[[38;5;9merror^[[0m^[[0m^[[1m: failed to build archive: Unknown attribute kind (86) (Producer: 'LLVM17.0.4' Reader: 'LLVM 15.0.6-rust-dev')^[[0m

^[[0m^[[1m^[[38;5;9merror^[[0m^[[0m^[[1m: aborting due to previous error^[[0m

will introduce a method for setting thinlto flags

Signed-off-by: minaripenguin <minaripenguin@users.noreply.github.com>